### ISSUE TITLE
Possibilité d'ignorer un attribut d'un modèle

### ISSUE THREAD

**Issue by nacben** [SamuelYvon/YAORM#7]
Par ex:

[PrimaryKey("NoVendeur", "")]
public class PPVendeurs : PersistableObject
{
    public int NoVendeur { get { return (int)PrimaryKey; } set { PrimaryKey = value; } }
    public String NomAffaires;
    public String XYZ -> ignorer

**Comment by SamuelYvon** [comment]
Est-ce que 

`[Ignore]
public string XYZ` serait pas mal?

**Comment by nacben** [comment]
Sounds good!

**Comment by SamuelYvon** [comment]
Added! Please close when you confirm it's what you want!

**Comment by nacben** [comment]
Thanks!
